### ISSUE TITLE
version windows has virus Trojan:Win32/Wacatac.B!ml

### ISSUE THREAD

**Issue by selique** [nguyenvanduocit/ai-commit#2]
version windows has virus Trojan:Win32/Wacatac.B!ml

**Comment by nguyenvanduocit** [comment]
Can you try to build it your self. I do not have window

1. Install Golang
2. Clone repo
3. run `go build ./...`

**Comment by selique** [comment]
![image](https://user-images.githubusercontent.com/1678894/222489468-25684e60-249c-47c5-a5b9-9e18c2d5cec1.png)
and why have release windows

**Comment by keres101** [comment]
🧐

**Comment by nguyenvanduocit** [comment]
I mean let's try to build your self to see if the build can be reported that has virus or not. The tool is build automatically via Github Action, not my computer.

**Comment by nguyenvanduocit** [comment]
You can alway build it your self.
