### ISSUE TITLE
Set up environment variable

### ISSUE THREAD

**Issue by UtkarshM-hub** [nguyenvanduocit/ai-commit#3]
How do I even set up the OPENAI_API_TOKEN environment variable.
It will be great if you guys include the steps to setup the environment variable into your README.md file

**Comment by nguyenvanduocit** [comment]
Setup env is depend on you os.

**Comment by UtkarshM-hub** [comment]
@nguyenvanduocit Even after setting the env it is showing me this
![image](https://user-images.githubusercontent.com/70505181/222920185-d469043c-84c8-4c25-af4b-8f75ff002cb1.png)

**Comment by nguyenvanduocit** [comment]
I will try to improve the prompt. I got this result sometimes

**Comment by anridev24** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/32931256/223056038-152149b7-ba75-41fb-b0ca-e4c6de3d1043.png)

Windows 10

after setting the API_KEY i get this message, any ideas?

**Comment by nguyenvanduocit** [comment]
There an mistake on the readme. The correct env key is OPENAI_API_KEY, not OPENAI_API_TOKEN. Sorry about that.

**Comment by UtkarshM-hub** [comment]
@nguyenvanduocit I've used the correct env but somehow still getting the same msg

**Comment by anridev24** [comment]
Same Error

**Comment by InternetJohnny** [comment]
Same error, `zsh: command not found: ai-commit`

**Comment by nguyenvanduocit** [comment]
Sorry, I was distract from this project, I am back, I think it's because ChatGPT can not under stand the diff

@InternetJohnny "Command not found: ai-commit" maybe because your PATH is not contains the binary

**Comment by nguyenvanduocit** [comment]
Just release new version. The new version will show more details about the error. I think it's because of usage or setup
