### ISSUE TITLE
zsh: command not found: ai-commit

### ISSUE THREAD

**Issue by GillHoang** [nguyenvanduocit/ai-commit#5]
I can not use your tool
![image](https://user-images.githubusercontent.com/89916615/227264664-65f1dd7a-0ae0-41ba-bf01-ea7bab125712.png)

**Comment by nguyenvanduocit** [comment]
as i see in the output, the tool is already run. but you did not set value for the env OPENAI_AI_KEY

**Comment by GillHoang** [comment]
> as i see in the output, the tool is already run. but you did not set value for the env OPENAI_AI_KEY

how to set??

**Comment by nguyenvanduocit** [comment]
It's depend on you OS, you can search Google for it. Here is the tutorial which answered by ChatGPT:

---

To set the OPENAI_API_KEY environment variable in Mac, Linux, and Windows, you can follow these steps:

Mac and Linux:

Open a terminal window
Type "export OPENAI_API_KEY=YOUR_API_KEY" (replace "YOUR_API_KEY" with your actual API key)
Press enter
Windows:

Press the Windows key + X and select "System" from the dropdown menu
Click on "Advanced system settings" on the left-hand side
Click on the "Environment Variables" button
Under "System variables," click "New"
In the "Variable name" field, enter "OPENAI_API_KEY"
In the "Variable value" field, enter your API key
Click "OK" to save the changes
Note: After setting the OPENAI_API_KEY environment variable, you will need to restart any applications or terminal windows that will be using it.
